/**
 * Mock feedback generator that simulates AI-powered feedback
 */

/**
 * Generate feedback based on submission content and score
 * This is a mock function that returns predefined feedback based on score ranges
 */
export function generateFeedback(content: string, score: number, subject: string): string {
  // In a real system, this would be generated by an LLM like Gemini
  
  // Get appropriate feedback templates based on subject
  const feedbackTemplates = getFeedbackTemplatesBySubject(subject);
  
  // Select feedback based on score range
  let feedbackTemplate = "";
  if (score >= 90) {
    feedbackTemplate = feedbackTemplates.excellent[Math.floor(Math.random() * feedbackTemplates.excellent.length)];
  } else if (score >= 80) {
    feedbackTemplate = feedbackTemplates.good[Math.floor(Math.random() * feedbackTemplates.good.length)];
  } else if (score >= 70) {
    feedbackTemplate = feedbackTemplates.average[Math.floor(Math.random() * feedbackTemplates.average.length)];
  } else {
    feedbackTemplate = feedbackTemplates.needsImprovement[Math.floor(Math.random() * feedbackTemplates.needsImprovement.length)];
  }
  
  // Check for specific keywords to make feedback more personalized
  let specificFeedback = "";
  
  // Add keyword-specific feedback based on subject
  switch (subject) {
    case "Mathematics":
      if (content.toLowerCase().includes("quadratic")) {
        specificFeedback = " Your understanding of quadratic equations is evident.";
      }
      if (content.toLowerCase().includes("formula")) {
        specificFeedback = " You've applied the formula correctly.";
      }
      break;
    case "Science":
      if (content.toLowerCase().includes("cell")) {
        specificFeedback = " Your explanation of cell structures is clear.";
      }
      if (content.toLowerCase().includes("function")) {
        specificFeedback = " Good connection between structure and function.";
      }
      break;
    case "English":
      if (content.toLowerCase().includes("theme")) {
        specificFeedback = " You've identified key themes effectively.";
      }
      if (content.toLowerCase().includes("character")) {
        specificFeedback = " Your character analysis is thoughtful.";
      }
      break;
    case "History":
      if (content.toLowerCase().includes("timeline")) {
        specificFeedback = " Your chronology of events is well organized.";
      }
      if (content.toLowerCase().includes("impact")) {
        specificFeedback = " Good analysis of historical impact.";
      }
      break;
  }
  
  // Return combined feedback
  return `${feedbackTemplate}${specificFeedback}`;
}

/**
 * Generate learning recommendations based on score and subject
 */
export function generateLearningRecommendations(score: number, subject: string): string[] {
  // In a real system, this would be based on content analysis and learning gaps
  const recommendations = [];
  
  // Add general recommendation based on score
  if (score < 70) {
    recommendations.push("Review core concepts and fundamentals");
  }
  
  // Add subject-specific recommendations
  switch (subject) {
    case "Mathematics":
      if (score < 80) {
        recommendations.push("Practice more problem-solving exercises");
        recommendations.push("Watch video tutorials on algebraic techniques");
      } else {
        recommendations.push("Try more advanced problems to challenge yourself");
      }
      break;
    case "Science":
      if (score < 80) {
        recommendations.push("Review textbook diagrams and illustrations");
        recommendations.push("Create concept maps to connect ideas");
      } else {
        recommendations.push("Explore laboratory experiments related to this topic");
      }
      break;
    case "English":
      if (score < 80) {
        recommendations.push("Practice writing more structured paragraphs");
        recommendations.push("Read more examples of literary analysis");
      } else {
        recommendations.push("Explore critical theory approaches to text analysis");
      }
      break;
    case "History":
      if (score < 80) {
        recommendations.push("Create detailed timelines to understand sequence of events");
        recommendations.push("Connect events to their broader historical context");
      } else {
        recommendations.push("Analyze primary source documents for deeper understanding");
      }
      break;
  }
  
  return recommendations;
}

/**
 * Helper function to get feedback templates by subject
 */
function getFeedbackTemplatesBySubject(subject: string) {
  // Default feedback templates
  const defaultTemplates = {
    excellent: [
      "Excellent work! Your understanding of the material is impressive.",
      "Outstanding job! You've demonstrated mastery of this topic.",
      "Exceptional work! Your response shows deep comprehension."
    ],
    good: [
      "Good job! Your understanding is solid with some room for improvement.",
      "Well done! You've shown good grasp of the key concepts.",
      "Nice work! Your response demonstrates good understanding."
    ],
    average: [
      "You've shown basic understanding but need to develop your ideas further.",
      "Your work demonstrates familiarity with the topic but lacks depth in places.",
      "You've covered the basics, but try to explore the concepts more thoroughly."
    ],
    needsImprovement: [
      "You need to review the fundamental concepts in this area.",
      "Your response shows some confusion about key concepts. Try reviewing the material.",
      "There are several misunderstandings in your work. Focus on the core principles."
    ]
  };
  
  // Subject-specific feedback templates
  switch (subject) {
    case "Mathematics":
      return {
        excellent: [
          "Excellent mathematical reasoning! Your solution process is clear and effective.",
          "Outstanding work! You've applied mathematical concepts with precision.",
          "Exceptional mathematical thinking! Your approach to problem-solving is sophisticated."
        ],
        good: [
          "Good mathematical work! Your calculations are mostly accurate with minor errors.",
          "Well done! Your problem-solving approach shows good understanding of mathematical concepts.",
          "Nice work! You've demonstrated good mathematical reasoning skills."
        ],
        average: [
          "You've shown basic mathematical understanding but need more precision in your calculations.",
          "Your work demonstrates familiarity with the formulas but lacks consistency in application.",
          "You've covered the basic mathematical concepts, but need to work on showing your steps clearly."
        ],
        needsImprovement: [
          "You need to review the mathematical formulas and concepts in this area.",
          "Your calculations contain several errors. Try working through problems step by step.",
          "Focus on understanding the fundamental mathematical principles before attempting complex problems."
        ]
      };
    case "Science":
      return {
        excellent: [
          "Excellent scientific analysis! Your understanding of the concepts is comprehensive.",
          "Outstanding scientific work! You've connected concepts and explained processes clearly.",
          "Exceptional scientific thinking! Your explanations demonstrate deep understanding of scientific principles."
        ],
        good: [
          "Good scientific work! Your explanations are mostly clear with a few minor misconceptions.",
          "Well done! Your scientific reasoning shows good understanding of the key processes.",
          "Nice scientific analysis! You've demonstrated good comprehension of the core concepts."
        ],
        average: [
          "You've shown basic scientific understanding but need to develop your explanations further.",
          "Your work demonstrates familiarity with scientific terminology but lacks depth in explanations.",
          "You've covered the basic scientific concepts, but try to connect ideas more thoroughly."
        ],
        needsImprovement: [
          "You need to review the scientific principles and processes in this area.",
          "Your explanations contain several misconceptions. Try revisiting the fundamental concepts.",
          "Focus on understanding the basic scientific principles before exploring more complex topics."
        ]
      };
    case "English":
      return {
        excellent: [
          "Excellent literary analysis! Your interpretation is insightful and well-supported.",
          "Outstanding written work! You've articulated complex ideas with clarity and evidence.",
          "Exceptional analysis! Your response demonstrates sophisticated understanding of the text."
        ],
        good: [
          "Good literary analysis! Your interpretation is thoughtful with room for deeper exploration.",
          "Well done! Your writing shows good critical thinking and textual understanding.",
          "Nice analysis! You've demonstrated good comprehension of the literary elements."
        ],
        average: [
          "You've shown basic literary understanding but need to support your ideas with more evidence.",
          "Your work demonstrates familiarity with the text but would benefit from more specific analysis.",
          "You've covered the basic themes, but try to explore the author's techniques more thoroughly."
        ],
        needsImprovement: [
          "You need to review the literary elements and analytical techniques for this text.",
          "Your analysis lacks specific evidence from the text. Try incorporating more quotes and examples.",
          "Focus on understanding the primary themes before moving to more nuanced interpretation."
        ]
      };
    case "History":
      return {
        excellent: [
          "Excellent historical analysis! Your understanding of events and their significance is comprehensive.",
          "Outstanding work in history! You've connected events and explained their context clearly.",
          "Exceptional historical thinking! Your analysis demonstrates deep understanding of cause and effect."
        ],
        good: [
          "Good historical work! Your chronology is accurate with thoughtful analysis of key events.",
          "Well done! Your historical reasoning shows good understanding of the period studied.",
          "Nice historical analysis! You've demonstrated good comprehension of the events and their significance."
        ],
        average: [
          "You've shown basic historical understanding but need to analyze the causes and effects further.",
          "Your work demonstrates familiarity with historical events but lacks depth in context.",
          "You've covered the basic timeline, but try to explore the significance of events more thoroughly."
        ],
        needsImprovement: [
          "You need to review the chronology and significance of historical events in this period.",
          "Your historical analysis contains several factual errors. Try creating a clear timeline of events.",
          "Focus on understanding the sequence of events before exploring more complex historical interpretations."
        ]
      };
    default:
      return defaultTemplates;
  }
} 